name: Go Build and Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.8" # Or use 'go-version-file: "go.mod"'

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -v ./...

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mtproto_stats
          path: app/
          retention-days: 1
